// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// ⚠️ STAGING ONLY: Este cliente apunta SIEMPRE al proyecto NUEVO (clonado)
const SUPABASE_URL = "https://eadocusarxgjbxuwiune.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhZG9jdXNhcnhnamJ4dXdpdW5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTI5NDUsImV4cCI6MjA3MDU2ODk0NX0.2EnCgBDt2Nict-sx7PQFD1R_FUcHE86JxAxYPcrCe3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
